x-common-variables: &common-variables
  POSTGRES_DB: tests
  POSTGRES_USER: user
  POSTGRES_PASSWORD: password

services:
  pytest:
    image: pytest:latest
    depends_on:
      - postgres
    environment: *common-variables
    networks:
      - tests

  postgres:
    image: postgres:14
    command: "postgres -c 'shared_buffers=512MB' -c 'fsync=off' -c 'synchronous_commit=off' -c 'full_page_writes=off' -c 'max_connections=200' -c 'client_min_messages=warning'"
    environment: *common-variables
    expose:
      - "5432"
    ports:
      - "5432:5432"
    networks:
      - tests

networks:
  tests:
    internal: true
