[project]
name = "GitTest"
version = "x"
description = ""
requires-python = ">=3.12"

[tool.black]
line-length = 100

[tool.ruff]
include = ["*.py"]
line-length = 100

[tool.isort]
profile = "black"
line_length = 100
reverse_relative = true
