name: 'Python Setup'
description: 'Python Setup description'
runs:
  using: "composite"
  steps:
    - name: Install uv
      uses: astral-sh/setup-uv@v6
      with:
        activate-environment: true
        enable-cache: true
        python-version: "3.12"

    - name: Get changed Python files
      id: changed-files
      uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c

    - name: List all changed files
      run: echo ${{ steps.changed-files.outputs.all_changed_files }}
      shell: sh
