name: Bandit

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

jobs:
  analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          python-version: "3.12"

      - name: Install Bandit
        run: uv pip install bandit

      - name: Run Bandit
        run: bandit --confidence-level high --severity-level medium -r *.py
