name: Bandit

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.12"]

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          python-version: ${{ matrix.python-version }}

      - name: Install Bandit
        run: uv pip install bandit

      - name: Run Bandit
        run: bandit --confidence-level high --severity-level medium -r *.py
