name: JavaScript code analysis

on:
  push:
  pull_request:

jobs:
  prettier:
    name: Prettier code formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Prettier
        run: npm install prettier

      - name: Check with Prettier
        run: |
          npx prettier --version
          npx prettier --check *.js
