name: JavaScript code analysis

on:
  push:
    paths:
      - '**.js'
      - '**.json'
      - '**.css'
      - '**.scss'
  pull_request:
    paths:
      - '**.js'
      - '**.json'
      - '**.css'
      - '**.scss'

jobs:
  prettier:
    name: Prettier code formatter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@ed68ef82c095e0d48ec87eccea555d944a631a4c # v46
        with:
          files: |
            **.js
            **.json
            **.css
            **.scss

      - name: Install Prettier
        run: npm install --no-audit --no-fund --loglevel=error prettier

      - name: Check with Prettier
        run: npx prettier --check ${{ steps.changed-files.outputs.all_changed_files }}
