name: Static Python code analysis

on:
  push:
  pull_request:

jobs:
  # Bandit is a tool designed to find common security issues in Python code.
  bandit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          activate-environment: true
          enable-cache: true
          python-version: "3.12"

      - name: Install Bandit
        run: uv pip install bandit

      - name: Run Bandit
        run: bandit --confidence-level high --severity-level medium -r *.py

  # Black Code formatter
  black:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Black Check
        uses: jpetrucciani/black-check@master
        with:
          path: '.'
          black_flags: '--exclude .venv/'
