name: Python code analysis

on:
  push:
  pull_request:

env:
  BLACK: 25.1.0
  ISORT: 6.0.1

jobs:
  # Bandit is a tool designed to find common security issues in Python code.
  bandit:
    name: Bandit security analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python

      - name: Install Bandit
        run: uv pip install bandit

      - name: Run Bandit
        run: bandit --confidence-level high --severity-level medium -r *.py

  # Black code formatter
  black:
    name: Black code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python

      - name: Install black
        run: uv pip install black==$BLACK

      - name: Run black
        run: black --check --verbose .

  isort:
    name: isort import validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/python

      - name: Install isort
        run: uv pip install isort==$ISORT

      - name: Run isort
        run: isort --check --verbose .
