name: Python code analysis

on:
  push:
    paths:
      - '**.py'
  pull_request:
    paths:
      - '**.py'

env:
  BLACK: 25.1.0
  ISORT: 6.0.1

jobs:
  # Bandit is a tool designed to find common security issues in Python code.
  bandit:
    name: Bandit security analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/python
        id: python

      - name: Install Bandit
        run: uv pip install bandit

      - name: Run Bandit
        run: bandit --confidence-level high --severity-level medium ${{ steps.python.outputs.changed_python_files }}

  # Black code formatter
  black:
    name: Black code formatting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/python
        id: python

      - name: Install black
        run: uv pip install black==$BLACK

      - name: Run black
        run: black --check --verbose ${{ steps.python.outputs.changed_python_files }}

  isort:
    name: isort import validation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: ./.github/actions/python
        id: python

      - name: Install isort
        run: uv pip install isort==$ISORT

      - name: Run isort
        run: isort --check --skip-gitignore --verbose ${{ steps.python.outputs.changed_python_files }}
