name: pytest

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker compose build

      - name: Run tests
        run: docker compose run --rm pytest

      - name: Remove containers
        run: docker compose down --remove-orphans