name: pytest

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to SWR
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.SWR_USER }}
          password: ${{ secrets.SWR_TOKEN }}

      - uses: actions/checkout@v4
      
      - name: Build Docker image
        run: docker compose build

      - name: Pull external Docker images
        run: docker compose pull --quiet --ignore-buildable

      - name: Run tests
        run: docker compose run --rm pytest

      - name: Remove containers
        run: docker compose down --remove-orphans