name: pytest

on:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Login to SWR
        uses: docker/login-action@v3
        with:
          registry: swr.eu-de.otc.t-systems.com
          username: ${{ secrets.SWR_USER }}
          password: ${{ secrets.SWR_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          load: true
          tags: pytest:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Checkout compose.yaml
        uses: actions/checkout@v4
        with:
          sparse-checkout: |
            compose.yaml
          sparse-checkout-cone-mode: false

      - name: Run tests
        run: docker compose run --quiet-pull --rm pytest

      - name: Remove containers
        run: docker compose down --remove-orphans